declare module 'react-redux'
declare module 'react-redux/es/hooks/useStore'
declare module 'react-redux/es/hooks/useSelector'
declare module 'react-redux/es/components/Provider'
declare module 'react-redux/es/utils/shallowEqual'
